<?php

declare(strict_types=1);

namespace Hirtz\Config\Migrations;

use yii\db\Migration;

/**
 * The squashed schema of this bundle, generated by `bin/baseline` from a fully migrated database.
 *
 * A fresh install runs this and nothing before it. An upgraded project never runs it: the collapse
 * writes this class into `migration` instead, having deleted the v2 rows it replaces.
 *
 * Raw SQL rather than the schema builder, and deliberately: the point of generating from a grown
 * database is that the fresh schema is what an upgraded one has, and a rewrite through the builder is
 * a chance for the two to differ. Regenerate rather than edit.
 *
 * The foreign keys come after every table, because `product` and `product_variant` reference each
 * other and no single `CREATE TABLE` can say that.
 *
 * @noinspection PhpUnused
 */
class M260101000800ConfigBaseline extends Migration
{
    public function safeUp(): void
    {
        $this->execute(<<<'SQL'
            INSERT INTO `auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `updated_at`, `created_at`) VALUES
              ('config', '2', '{\"category\":\"config\",\"key\":\"AUTH_CONFIG_DESCRIPTION\"}', NULL, NULL, '1789985581', '1789985581')
            SQL);

        $this->execute(<<<'SQL'
            INSERT INTO `auth_item_child` (`parent`, `child`) VALUES
              ('admin', 'config'),
              ('manager', 'config')
            SQL);
    }

    public function safeDown(): bool
    {
        echo "    > a baseline cannot be reverted, restore a dump instead\n";

        return false;
    }
}
